apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: hatohui/log-output@sha256:4083377bb8363158edfcecb8aef72cef08ab708b19528e48dfee2897ee1857cb
