name: log-output

services:
  log-output:
    image: hatohui/log-output:latest
    build: .
    container_name: log-output
    ports:
      - "3000:3000"
    environment:
      - LOG_LEVEL=info
    restart: always
